"use strict";

var { _, eq, ok, async, immediate } = require('./common.js');

test("defer one", function(done){

   await{ async.echo(defer(var one), 1); }

   eq(one, 1);

   done();

});


test("defer immediate", function(done){

   await{ immediate(defer(var one), 1); }

   eq(one, 1);

   done();

});

test("defer many", function(done){

   var time = _.timestamp();

   await{ 
      async.wait(defer(var one), 10);
      async.wait(defer(var two), 20);
      async.wait(defer(var three), 30);
   }

   time = _.timestamp() - time;

   ok(time >= 30 && time < 40); // if they run in series they'd take 60ms minimum

   eq(one, 10);
   eq(two, 20);
   eq(three, 30);

   done();

});

test("defer many with immediate", function(done){
   
   var time = _.timestamp();

   await{ 
      immediate(defer(var one), 0);
      async.wait(defer(var two), 20);
      async.wait(defer(var three), 30);
   }

   time = _.timestamp() - time;

   ok(time >= 30 && time < 40); // if they run in series they'd take 50ms minimum

   eq(one, 0);
   eq(two, 20);
   eq(three, 30);

   done();

});
