"use strict";

var { _, eq, ok, timer, async } = require('./common.js');

test("defer many", function(done){

   var time = timer();

   await{ 
      async.echo(100, defer(var one), 1);
      async.echo(200, defer(var two), 2);
      async.echo(300, defer(var three), 3);
   }


   time(300, 50);

   eq(one, 1);
   eq(two, 2);
   eq(three, 3);

   done();

});

test("defer many with immediate", function(done){
   
   var time = timer();

   await{ 
      async.echo(-1, defer(var one), 1);
      async.echo(200, defer(var two), 2);
      async.echo(300, defer(var three), 3);
   }

   time(300, 50);

   eq(one, 1);
   eq(two, 2);
   eq(three, 3);

   done();

});
