"use strict";

var _ = require('dry-underscore');
var eq = _.test.eq;
var ok = _.test.ok;

var res = 0;
var i = 0;

test("another test of continue and break", function(done){
   (function (cb) {
      foo : while (i < 100) {
         await { setTimeout (defer (), 10*Math.random()); }

         if (i == 10) {
            i += 2;
            res |= (1 << 20);
            continue foo;
         }

         res |= (1 << i);

         if (i == 3) {
            i++;
            res |= (1 << 21);
         }

         if (i == 13) {
            res |= (1 << 22);
            break foo;
         }
         i++;
      }
      res |= (1 << 23);
      cb();
   })(function(){
      ok((res == 15741935 && i == 13), "all bits set!");
      done();
   });
});
