"use strict";

var _ = require('dry-underscore');
var eq = _.test.eq;
var ok = _.test.ok;

var i = 0;
var n = 11;

test("a test of return", function(done){

   (function(cb){
      while (i < n + 4) {
         await { setTimeout (defer (), 10 * Math.random ()); }
         i++;
         if (i == n) {
            cb ();
            return;
         }
      }
   })(function(){
      eq(i, n, "return at right moment");
      done();
   })
});
