"use strict";

var _ = require('dry-underscore');
var eq = _.test.eq;
var ok = _.test.ok;

function MyClass (lim) {
   this._i = 0;
   this._lim = lim;

   this.iter = function () { return this._i; }

   this.next = function (cb) {
      var done = false;
      if (this._i >= this._lim) {
         done = true;
      } else {
         await { setTimeout (defer (), 3 * Math.random ()); }
         this._i ++;
      }
      cb (done);
   };
};

var obj = null;
var n = 30;

test("test of 'this' inside of a tamed class", function(fin){

   (function(cb){
      obj = new MyClass (n);
      var done = false;
      while (!done) {
         await { obj.next (defer (done)); }
      }
      cb();
   })(function(){
      eq(obj.iter(), n, "achieved n iterations");
      fin();
   });

});

