"use strict";

var _ = require('dry-underscore');
var eq = _.test.eq;
var ok = _.test.ok;

var res = 0;
var i = 0;

function Class () {

   this._v = [];

   for (var i = 0; i < 10; i++) { this._v.push (i); }

   this.run = function (cb) {
      this._u = [];
      for (var i in this._v) {
         this._u.push (this._v[i]);
         await { setTimeout (defer (), 10*Math.random ()); }
      }
      cb ();
   };

   this.check = function () {
      return JSON.stringify (this._v) == JSON.stringify (this._u);
   };

};

var obj = new Class ();

test("a test of for (var i in this._foo)", function(done){

   (function(cb){
      await { obj.run (defer ()); }
      cb();
   })(function(){
      ok(obj.check(), "made it through 10 times");
      done();
   });

});
