"use strict";

var _ = require('dry-underscore');
var eq = _.test.eq;
var ok = _.test.ok;

var res = 0;
var i = 0;

function foo (i, cb) {
   await { setTimeout (defer (), i); }
   cb (i);
};


var flag = true;

test("a test of fulfill values", function(done){

   (function(cb){

      for (var i = 0; i < 20; i++) {
         var x = 3 * Math.random ();
         await { foo (x, defer (var y, z)); }
         if (x != y) { flag = false; }
      }

      for (var i = 0; i < 20; i++) {
         var x = 3 * Math.random ();
         await { foo (x, defer (var res)); }
         if (x != res) { flag = false; }
      }

      cb();

   })(function () {
      ok(flag, "fulfilled with proper values");
      done();
   });

});
