
var _ = require('dry-underscore');
var eq = _.test.eq;
var ok = _.test.ok;

var slots = {};
var env = { i : 0, n : 10, sum : 0 };

test("test with{} statements", function(done){

   (function(cb){

      with (env) {
         while (i < n) {
            await { 
               setTimeout (defer (), 3*Math.random ()); 
            }
            sum += i;
            i++;
         }
      }
      cb();
   })(function(){
      ok( (env.i == env.n && env.sum == 45), "env was properly modified"); 
      done();
   });
});
