"use strict";

var _ = require('dry-underscore');
var eq = _.test.eq;
var ok = _.test.ok;

var slots = {};
var n = 40;
var assert = require ("assert");

test("simple parallel await", function(done){
    
   (function(cb){
      var i = 0;	
      while (i < n) {
         await { 
            setTimeout (defer (), 1); 
            setTimeout (defer (), 2); 
         }
         slots[i] = 1;
         i++;
      }
      cb();
   })(function(){
	    for (var i = 0; i < n; i++) {
	        ok(slots[i], "slot[" + i + "] is set");
	    }
       done();
    });
});
