"use strict";

var _ = require('dry-underscore');
var eq = _.test.eq;
var ok = _.test.ok;

var n = 30;
var skip = 20;
var slots = {};

test("break and continue", function(done){

   (function(cb){
      var i = 0;
      while (1) {
         slots[i] = 0;
         await { setTimeout (defer (), 1); }

         if (i == skip) {
            i++;
            continue;
         }
         slots[i] = 1;
         i++;
         if (i == n) {
            break;
         }
      }
      cb();
   })(function(){
      var i = 0;
      for (i = 0; i < n; i++) {
         if (i != skip) {
            ok(slots[i], "iter " + i + ": all slots but skip=" + skip);
         } else {
            ok(!slots[i], "iter " + i + ":  all slots but skip=" + skip);
         }
      }
      ok(!slots[i], "stop at slot=" + n);
      done();
   });

});
