"use strict";

var _ = require('dry-underscore');
var eq = _.test.eq;
var ok = _.test.ok;

var listA = [];
var listB = [];


test("for..in iteration 01", function(done){

    (function(cb){
	    var i = 0;
	    for (i = 0; i < 10; i++) {
	        await { setTimeout (defer (), 10* Math.random ()); }
	        listA.push (i);
	    }
	    for ( ; i < 20; i++) {
	        listA.push (i);
	    }
	    while (true) {
	        if (i >= 30) {
		        break;
	        }
	        await { setTimeout (defer (), 10* Math.random ()); }
	        listA.push (i);
	        i++;
	    }
	    while (true) {
	        if (i >= 40) {
		        break;
	        }
	        listA.push (i);
	        i++;
	    }
	    cb ();
    })(function(){
	    for (var i = 0; i < 40; i++) { listB.push (i); }
	    eq(listA, listB, "list equivalence");
       done();
    });
});
