"use strict";

var _ = require('dry-underscore');
var eq = _.test.eq;
var ok = _.test.ok;

var res = 0;

function foo (cb) {
    await { setTimeout (defer (), 10 * Math.random ()); }
    res++;
    cb();
};

test("parser variations 00", function(done){
    
    (function(cb){
	    if (true) await{ foo (defer ()); }
	    res++;
	    cb();
    })(function(){
	    eq(res, 2, "both increments fired");
       done();
    });

});
